package com.hxq.mobile.weixin.repository;

import com.hxq.mobile.entity.weixin.CsZySubject;
import com.wxcommon.mybatis.MyBatisRepository;

import java.util.List;

@MyBatisRepository
public interface CsZySubjectDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_zy_subject
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_zy_subject
     *
     * @mbggenerated
     */
    int insert(com.hxq.mobile.entity.weixin.CsZySubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_zy_subject
     *
     * @mbggenerated
     */
    CsZySubject selectByPrimaryKey(String id);

    /**
     * 查找所有的量表
     * @return list
     */
    List<CsZySubject> selectAll(String self);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_zy_subject
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CsZySubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_zy_subject
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(com.hxq.mobile.entity.weixin.CsZySubject record);

    CsZySubject selectNextSubject(CsZySubject csZySubject);

    List<CsZySubject> queryByPid(String parentId);
}