package com.hxq.mobile.doctor.common.mapper;

import com.hxq.mobile.entity.common.StaffLoginStatus;
import com.wxcommon.mybatis.MyBatisRepository;

@MyBatisRepository
public interface StaffLoginStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_login_status
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_login_status
     *
     * @mbggenerated
     */
    int insert(StaffLoginStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_login_status
     *
     * @mbggenerated
     */
    int insertSelective(StaffLoginStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_login_status
     *
     * @mbggenerated
     */
    StaffLoginStatus selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_login_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StaffLoginStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_login_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaffLoginStatus record);

    StaffLoginStatus selectByDoctorUuid(String doctorUuid);
}