package com.hxq.mobile.weixin.service;

import com.hxq.mobile.entity.weixin.CsZyItem;

import java.util.List;

public interface CsZyItemService {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_zy_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_zy_item
     *
     * @mbggenerated
     */
    int insert(CsZyItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_zy_item
     *
     * @mbggenerated
     */
    int insertSelective(CsZyItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_zy_item
     *
     * @mbggenerated
     */
    CsZyItem selectByPrimaryKey(String id);

    /**
     * 根据专业测试的id查找题目
     * @param subjectId subjectid
     * @return list
     */
    List<CsZyItem> selectBySubjectId(String subjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_zy_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CsZyItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_zy_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CsZyItem record);
}