package com.hxq.mobile.entity.weixin;

public class CsZyItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_zy_item.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_zy_item.subject_id
     *
     * @mbggenerated
     */
    private String subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_zy_item.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_zy_item.input_type
     *
     * @mbggenerated
     */
    private String inputType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_zy_item.input_text
     *
     * @mbggenerated
     */
    private String inputText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_zy_item.input_value
     *
     * @mbggenerated
     */
    private String inputValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_zy_item.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_zy_item.id
     *
     * @return the value of cs_zy_item.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_zy_item.id
     *
     * @param id the value for cs_zy_item.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_zy_item.subject_id
     *
     * @return the value of cs_zy_item.subject_id
     *
     * @mbggenerated
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_zy_item.subject_id
     *
     * @param subjectId the value for cs_zy_item.subject_id
     *
     * @mbggenerated
     */
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId == null ? null : subjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_zy_item.content
     *
     * @return the value of cs_zy_item.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_zy_item.content
     *
     * @param content the value for cs_zy_item.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_zy_item.input_type
     *
     * @return the value of cs_zy_item.input_type
     *
     * @mbggenerated
     */
    public String getInputType() {
        return inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_zy_item.input_type
     *
     * @param inputType the value for cs_zy_item.input_type
     *
     * @mbggenerated
     */
    public void setInputType(String inputType) {
        this.inputType = inputType == null ? null : inputType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_zy_item.input_text
     *
     * @return the value of cs_zy_item.input_text
     *
     * @mbggenerated
     */
    public String getInputText() {
        return inputText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_zy_item.input_text
     *
     * @param inputText the value for cs_zy_item.input_text
     *
     * @mbggenerated
     */
    public void setInputText(String inputText) {
        this.inputText = inputText == null ? null : inputText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_zy_item.input_value
     *
     * @return the value of cs_zy_item.input_value
     *
     * @mbggenerated
     */
    public String getInputValue() {
        return inputValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_zy_item.input_value
     *
     * @param inputValue the value for cs_zy_item.input_value
     *
     * @mbggenerated
     */
    public void setInputValue(String inputValue) {
        this.inputValue = inputValue == null ? null : inputValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_zy_item.sort
     *
     * @return the value of cs_zy_item.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_zy_item.sort
     *
     * @param sort the value for cs_zy_item.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}