package com.hxq.mobile.common.mapper;

import com.hxq.mobile.entity.common.BasicdataAreaProvince;
import com.wxcommon.mybatis.MyBatisRepository;

import java.util.List;

@MyBatisRepository
public interface BasicdataAreaProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicdata_area_province
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicdata_area_province
     *
     * @mbggenerated
     */
    int insert(BasicdataAreaProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicdata_area_province
     *
     * @mbggenerated
     */
    int insertSelective(BasicdataAreaProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicdata_area_province
     *
     * @mbggenerated
     */
    BasicdataAreaProvince selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicdata_area_province
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BasicdataAreaProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basicdata_area_province
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BasicdataAreaProvince record);

    List<BasicdataAreaProvince> selectAll();
}