package com.hxq.mobile.common.mapper;

import com.hxq.mobile.entity.common.HospitalInfo;
import com.wxcommon.mybatis.MyBatisRepository;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MyBatisRepository
public interface HospitalInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_info
     *
     * @mbggenerated
     */
    int insert(HospitalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_info
     *
     * @mbggenerated
     */
    int insertSelective(HospitalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_info
     *
     * @mbggenerated
     */
    HospitalInfo selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HospitalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HospitalInfo record);

    List<HospitalInfo> selectHospital(@Param("provinceUuid") String provinceUuid, @Param("cityUuid") String cityUuid, @Param("regionUuid") String regionUuid);
}